FROM rocm/dev-ubuntu-22.04:6.4-complete

RUN apt-get update -y && \
    apt-get install -y \
    git \
    cmake \
    meson \
    ninja-build \
    pybind11-dev \
    autoconf \
    libtool

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    python3-venv \
    infiniband-diags \
    net-tools \
    rdma-core \
    ibverbs-utils

RUN cd /usr/local/src && \
    git clone https://github.com/openucx/ucx.git && \
    cd ucx &&                   \
    git checkout v1.19.x &&     \
    ./autogen.sh && ./configure \
    --prefix=/usr/local         \
    --enable-shared             \
    --disable-static            \
    --disable-doxygen-doc       \
    --enable-optimizations      \
    --enable-cma                \
    --enable-devel-headers      \
    --with-rocm=/opt/rocm       \
    --with-verbs                \
    --with-efa                  \
    --with-dm                   \
    --enable-mt &&              \
    make -j &&                  \
    make -j install-strip &&    \
    ldconfig

ENV LD_LIBRARY_PATH=/usr/local/lib
ENV PATH=/usr/local/bin:$PATH

RUN cd /usr/local/src && git clone https://github.com/ai-dynamo/nixl.git && \
    cd nixl && \
    pip install meson -U && \
    mkdir build && \
    meson setup build/ --prefix=/usr/local -Ddisable_gds_backend=true && \
    cd build/ && \
    ninja && \
    ninja install

RUN ln -s /usr/bin/python3 /usr/bin/python

CMD ["bash"]