# Itself based on: quay.io/pypa/manylinux_2_28_x86_64@sha256:d632b5e68ab39e59e128dcf0e59e438b26f122d7f2d45f3eea69ffd2877ab017
ARG BASE_IMAGE=ghcr.io/rocm/therock_build_manylinux_x86_64@sha256:3ac188c17f88f08ce522297b616d8308361b8e9a9b31bcc3c3bbb9429b1efa6c

FROM ${BASE_IMAGE}

# ---------------------------------------------------------------------------
# Basic build & runtime dependencies (minus ROCm which is already in base)
#
# Note that the PyPA manylinux upstream has all python versions pre-installed
# ---------------------------------------------------------------------------
RUN dnf install -y rdma-core rdma-core-devel glog glog-devel gflags gflags-devel gtest gtest-devel\
    elfutils-libelf elfutils-libelf-devel hiredis hiredis-devel libnl3 libnl3-devel unzip

WORKDIR /io

CMD ["bash"]
