name: Remote UCCL Build & Verify

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: remote-uccl-build
  cancel-in-progress: true

jobs:
  build-on-gpu-host:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout (for artifacts/consistency)
        uses: actions/checkout@v4

      - name: Setup SSH for l4-sky-test-01
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "${{ secrets.L4_SSH_KEY }}" > ~/.ssh/l4_key
          chmod 600 ~/.ssh/l4_key

          cat >> ~/.ssh/config <<'EOF'
          Host l4-sky-test-01
            HostName 4.14.153.89
            User skytestuser
            IdentityFile ~/.ssh/l4_key
            IdentitiesOnly yes
          EOF

          ssh-keyscan -H 4.14.153.89 >> ~/.ssh/known_hosts

      - name: Sync PR code to remote
        shell: bash
        run: |
          set -euo pipefail
          git submodule update --init --recursive thirdparty/nccl
          rsync -az --delete \
            -e "ssh -o BatchMode=yes" \
            ./gpu_driven ./rdma ./p2p \
            ./ l4-sky-test-01:/home/skytestuser/uccl-test/

      - name: Build & verify UCCL on remote
        shell: bash
        run: |
          set -euo pipefail
          ssh -o BatchMode=yes l4-sky-test-01 'bash -lc "
            set -euo pipefail

            # Explicitly load the right conda init
            source \$HOME/miniconda3/etc/profile.d/conda.sh

            if ! command -v conda >/dev/null 2>&1; then
              echo \"conda not found even after sourcing\" >&2
              exit 1
            fi

            # Create env if missing
            conda info --envs | awk \x27{print \$1}\x27 | grep -qx uccl || conda create -y -n uccl python=3.11
            conda activate uccl

            cd /home/skytestuser/uccl-test
            ./build_and_install.sh cuda all 3.11 2>&1 | tee build.log

            grep -q \"Successfully installed uccl-0.0.1.post4\" build.log
          "'

      - name: Fetch remote build.log
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          scp -o BatchMode=yes l4-sky-test-01:/home/skytestuser/uccl-test/build.log ./build.log || true

      - name: Upload build.log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
