# Makefile for jring example

CXX = g++
CXXFLAGS = -Wall -O2 -I../.. -I../../include -pthread
LDFLAGS = -pthread

TARGET = jring_example
SRC = jring_example.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $@ $< $(LDFLAGS)

clean:
	rm -f $(TARGET)

run: $(TARGET)
	./$(TARGET)

.PHONY: all clean run
